<!DOCTYPE html>
<html lang="en">
<style>
    .searchGrid{
        display: grid;
        grid-template-columns: 10% 1fr;
        grid-template-rows: 100px;
        align-items: center
    }
    h3{

    }
    #form{
        display: grid;
        grid-template-columns: 20% 20% 20% 20% 20%;
    }
</style>
<h1>Featured Talent</h1>
<div class="searchGrid">
    <h3 id="searchText">Search Filter</h3>
    <form action="/action_page.php" id="form">
        <div class="checkbox">
            <input type="checkbox" id="example1" name="example1" value="example1">
            <label for="example1">example1</label>
        </div>
        <div class="checkbox">
            <input type="checkbox" id="example2" name="example2" value="example2">
            <label for="example2">example2</label>
        </div>
        <div class="checkbox">
            <input type="checkbox" id="example3" name="example3" value="example3">
            <label for="example3">example3</label>
        </div>
        <div class="checkbox">
            <input type="checkbox" id="example4" name="example4" value="example4">
            <label for="example4">example4</label>
        </div>
        <div class="checkbox">
            <input type="checkbox" id="example5" name="example5" value="example5">
            <label for="example5">example5</label>
        </div>
    </form>
</div>
</html>