<!-- css -->
<link href="/css/index.css" rel="stylesheet">
<?php require_once 'template/header.phtml';?>

<?php require_once 'homepage/section1.html';?>
    <div id="space"></div>
<?php require_once 'homepage/Featured Talent.html';?>
    <div class="the-grid">
        <div class="leftSection">
        <?php require_once 'homepage/Section3Paragraph.html';?>
        <?php require_once 'homepage/twitter.html';?>
        </div>
        <?php require_once 'homepage/MailForm.html';?>
    </div>
    <div id="space"></div>
<?php require_once 'template/footer.html';?>