<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.css">
    <!-- css -->
    <link href="/css/header.css" rel="stylesheet">

    <title>One Media Agency - <?php echo $view->pageTitle; ?></title>
</head>
    <ul class="navbar-grid">
        <li><a href="/index.php">Home</a></li>
        <li><a href="/talent.php">Talent</a></li>
        <img id="headerImage" src="/Images/header.png"></a>
        <li class="right"><a href="#example">Example</a></li>
        <li class="right"><a href="#example">Example</a></li>
    </ul>
<header class="navbar-mobile">
    <img id="headerImage" src="/Images/header.png">
    <button id="hamburger">☰</button>
</header>
<div class="dropdown">
    <ul class="navbar-dropdown">
        <li><a  href="/index.php">Home</a></li>
        <li><a href="/talent.php">Talent</a></li>
        <li class="right"><a href="#example">Example</a></li>
        <li class="right"><a href="#example">Example</a></li>
    </ul>
</div>
<body>